"use client";

import { useEffect, useState } from "react";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { ClaveDocumento, CriterioRubrica, DOCUMENTOS_EQUIPO, RUBRICA_GENERICA, RubricasPorDocumento } from "@/types";
import { Save } from "lucide-react";

const inicial = (): RubricasPorDocumento => Object.fromEntries(DOCUMENTOS_EQUIPO.map(({ clave }) => [clave, RUBRICA_GENERICA.map((c) => ({ ...c }))])) as RubricasPorDocumento;
export default function RubricasAdminPage() {
  const [rubricas, setRubricas] = useState<RubricasPorDocumento>(inicial); const [documento, setDocumento] = useState<ClaveDocumento>(DOCUMENTOS_EQUIPO[0].clave); const [guardando, setGuardando] = useState(false); const [mensaje, setMensaje] = useState("");
  useEffect(() => { getDoc(doc(db, "configuracion", "rubrica")).then((s) => { if (s.exists() && s.data().rubricas) setRubricas({ ...inicial(), ...s.data().rubricas }); }); }, []);
  function cambiar(index: number, campo: keyof CriterioRubrica, valor: string) { setRubricas((actual) => ({ ...actual, [documento]: actual[documento].map((criterio, i) => i === index ? { ...criterio, [campo]: campo === "puntosMax" ? Number(valor) : valor } : criterio) })); }
  async function guardar() { setGuardando(true); await setDoc(doc(db, "configuracion", "rubrica"), { rubricas }); setMensaje("Las tres rúbricas quedaron guardadas."); setGuardando(false); }
  return <main className="p-4 sm:p-6 md:p-8 max-w-5xl mx-auto space-y-6"><div><p className="text-sm text-[#c8102e] font-semibold uppercase tracking-wider">Configuración administrativa</p><h1 className="text-3xl font-bold text-[#202124]">Rúbricas por documento</h1><p className="text-gray-500 mt-2">Cada documento tiene su propia rúbrica editable. Un proyecto puede recibir múltiples evaluaciones.</p></div><div className="flex flex-col sm:flex-row gap-2">{DOCUMENTOS_EQUIPO.map(({ clave, nombre }) => <button key={clave} onClick={() => setDocumento(clave)} className={`px-4 py-3 text-sm font-semibold border text-left ${documento === clave ? "bg-[#c8102e] text-white border-[#c8102e]" : "bg-white text-gray-700 border-gray-300"}`}>{nombre}<span className="block text-xs font-normal opacity-80">{rubricas[clave].length} criterios</span></button>)}</div><section className="bg-white border border-gray-200"><div className="p-4 sm:p-5 border-b"><h2 className="font-bold text-lg text-[#202124]">{DOCUMENTOS_EQUIPO.find((d) => d.clave === documento)?.nombre}</h2><p className="text-sm text-gray-500">Edita el nombre y puntaje máximo de cada criterio.</p></div><div className="divide-y">{rubricas[documento].map((criterio, index) => <div key={index} className="p-4 grid grid-cols-[32px_1fr] sm:grid-cols-[40px_1fr_120px] gap-3 items-center"><span className="w-8 h-8 rounded-full bg-red-50 text-[#c8102e] flex items-center justify-center font-bold text-sm">{index + 1}</span><input value={criterio.criterio} onChange={(e) => cambiar(index, "criterio", e.target.value)} className="border border-gray-300 px-3 py-2 text-gray-900" /><label className="col-start-2 sm:col-start-auto text-xs text-gray-500">Puntos máximos<input type="number" min="1" value={criterio.puntosMax} onChange={(e) => cambiar(index, "puntosMax", e.target.value)} className="w-full border border-gray-300 px-3 py-2 text-gray-900 mt-1" /></label></div>)}</div></section><div className="flex items-center gap-4"><button onClick={guardar} disabled={guardando} className="bg-[#c8102e] text-white px-5 py-2.5 font-semibold flex items-center gap-2 disabled:opacity-50"><Save size={17} />{guardando ? "Guardando..." : "Guardar las 3 rúbricas"}</button>{mensaje && <span className="text-sm text-green-700">{mensaje}</span>}</div></main>;
}
