"use client";

import { useEffect, useState } from "react";
import { escucharUsuarios } from "@/lib/usuarios";
import { Usuario, Rol } from "@/types";
import { useAuth } from "@/components/AuthProvider";

export default function UsuariosAdminPage() {
  const [usuarios, setUsuarios] = useState<Usuario[]>([]);
  const [nombre, setNombre] = useState(""); const [correo, setCorreo] = useState(""); const [password, setPassword] = useState(""); const [rol, setRol] = useState<Rol>("maestro"); const [mensaje, setMensaje] = useState(""); const [guardando, setGuardando] = useState(false);
  const { user } = useAuth();
  useEffect(() => escucharUsuarios(setUsuarios), []);
  async function crearUsuario(e: React.FormEvent) { e.preventDefault(); setGuardando(true); setMensaje(""); try { const token = await user?.getIdToken(); const response = await fetch("/api/admin/usuarios", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ nombre, correo, password, rol }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMensaje(`Usuario creado como ${rol}. Debe iniciar sesión con ${correo}.`); setNombre(""); setCorreo(""); setPassword(""); } catch (error) { setMensaje(error instanceof Error ? error.message : "No se pudo crear el usuario"); } finally { setGuardando(false); } }
  async function cambiarRol(uid: string, nuevoRol: Rol) { const token = await user?.getIdToken(); const response = await fetch("/api/admin/usuarios", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ uid, rol: nuevoRol }) }); if (!response.ok) { const data = await response.json(); setMensaje(data.error ?? "No se pudo cambiar el rol"); return; } setUsuarios((actuales) => actuales.map((u) => u.uid === uid ? { ...u, rol: nuevoRol } : u)); setMensaje("Rol actualizado. La persona debe cerrar sesión y volver a entrar."); }
  return <div className="p-6 space-y-6"><div><h1 className="text-2xl font-bold">Usuarios y roles</h1><p className="text-sm text-gray-500 mt-1">Crea cuentas y asigna uno de los dos roles. El rol queda guardado en Firebase Authentication como claim.</p></div><form onSubmit={crearUsuario} className="bg-white border border-gray-200 p-4 grid grid-cols-1 md:grid-cols-5 gap-3"><input required placeholder="Nombre completo" value={nombre} onChange={(e) => setNombre(e.target.value)} className="border px-3 py-2" /><input required type="email" placeholder="Correo" value={correo} onChange={(e) => setCorreo(e.target.value)} className="border px-3 py-2" /><input required minLength={6} type="password" placeholder="Contraseña temporal" value={password} onChange={(e) => setPassword(e.target.value)} className="border px-3 py-2" /><select value={rol} onChange={(e) => setRol(e.target.value as Rol)} className="border px-3 py-2"><option value="maestro">Maestro</option><option value="admin">Administrador</option></select><button disabled={guardando} className="bg-[#D7282F] text-white px-3 py-2 disabled:opacity-50">{guardando ? "Creando..." : "Crear usuario"}</button>{mensaje && <p className="md:col-span-5 text-sm text-gray-600">{mensaje}</p>}</form><div className="bg-white border border-gray-200 overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-100 text-left"><tr><th className="p-3">Nombre</th><th className="p-3">Correo</th><th className="p-3">Rol</th></tr></thead><tbody>{usuarios.map((usuario) => <tr key={usuario.uid} className="border-t"><td className="p-3">{usuario.nombre || "Sin nombre"}</td><td className="p-3">{usuario.correo}</td><td className="p-3"><select value={usuario.rol === "admin" || usuario.rol === "maestro" ? usuario.rol : "maestro"} onChange={(e) => cambiarRol(usuario.uid, e.target.value as Rol)} className="border px-2 py-1 text-xs"><option value="maestro">maestro</option><option value="admin">admin</option></select></td></tr>)}{usuarios.length === 0 && <tr><td colSpan={3} className="p-6 text-center text-gray-400">No hay usuarios en la colección usuarios.</td></tr>}</tbody></table></div><p className="text-xs text-gray-500">Al cambiar un rol, la persona debe cerrar sesión y volver a entrar para recibir el nuevo claim.</p></div>;
}
