"use client";

import { useState } from "react";
import { DOCUMENTOS_EQUIPO, DatosRegistroEquipo, Equipo } from "@/types";
import { actualizarEquipo, crearEquipo } from "@/lib/equipos";
import { X } from "lucide-react";

const CAMPOS: { key: keyof DatosRegistroEquipo; label: string; type?: string }[] = [
  { key: "nombreCompleto", label: "Nombre completo" }, { key: "numeroTelefonico", label: "Número telefónico", type: "tel" }, { key: "email", label: "E-mail", type: "email" }, { key: "edad", label: "Edad" }, { key: "genero", label: "Género" }, { key: "nivelEstudios", label: "Nivel de estudios" }, { key: "campusUvmCercano", label: "Campus UVM cercano" }, { key: "matriculaLider", label: "Matrícula del líder del equipo" }, { key: "carreraLider", label: "Carrera del líder de equipo" }, { key: "numeroIntegrantes", label: "Número de integrantes", type: "number" }, { key: "nombreProyecto", label: "Nombre del proyecto" }, { key: "clasificacionProyecto", label: "Clasificación del proyecto" }, { key: "cuentaCon", label: "El proyecto a participar cuenta con" },
];
const VACIO: DatosRegistroEquipo = { nombreCompleto: "", numeroTelefonico: "", email: "", edad: "", genero: "", nivelEstudios: "", campusUvmCercano: "", matriculaLider: "", carreraLider: "", numeroIntegrantes: 1, nombreProyecto: "", clasificacionProyecto: "", cuentaCon: "" };
const input = "w-full px-3 py-2.5 border border-gray-300 text-gray-900 bg-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-[#c8102e] focus:border-[#c8102e]";

export function ModalEquipo({ equipo, onClose }: { equipo: Equipo | null; onClose: () => void }) {
  const [registro, setRegistro] = useState<DatosRegistroEquipo>(equipo?.registro ?? { ...VACIO, nombreCompleto: equipo?.representante?.nombre ?? "", numeroTelefonico: equipo?.representante?.telefono ?? "", email: equipo?.representante?.correo ?? "", nombreProyecto: equipo?.nombreEquipo ?? "", numeroIntegrantes: equipo?.integrantes?.length || 1 });
  const [documentos, setDocumentos] = useState(equipo?.documentos ?? []); const [guardando, setGuardando] = useState(false); const [error, setError] = useState("");
  function cambiar(campo: keyof DatosRegistroEquipo, valor: string) { setRegistro((actual) => ({ ...actual, [campo]: campo === "numeroIntegrantes" ? Number(valor) || 0 : valor })); }
  async function guardar() { setError(""); if (Object.values(registro).some((v) => v === "" || v === 0)) { setError("Completa todos los campos del registro."); return; } setGuardando(true); try { const data = { nombreEquipo: registro.nombreProyecto, integrantes: [{ nombre: registro.nombreCompleto, apellido: "", matricula: registro.matriculaLider }], representante: { nombre: registro.nombreCompleto, telefono: registro.numeroTelefonico, correo: registro.email }, registro, documentos, fechaAlta: equipo?.fechaAlta ?? new Date().toISOString(), ...(equipo?.codigoProyecto ? { codigoProyecto: equipo.codigoProyecto } : {}) }; if (equipo) await actualizarEquipo(equipo.id, data); else await crearEquipo(data); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar el proyecto."); } finally { setGuardando(false); } }
  return <div className="fixed inset-0 z-50 bg-black/60 p-3 sm:p-6 flex items-center justify-center"><div className="bg-white w-full max-w-4xl max-h-[94vh] overflow-y-auto"><div className="sticky top-0 z-10 bg-white border-b px-5 sm:px-7 py-4 flex items-center justify-between"><div><p className="text-xs text-[#c8102e] font-bold uppercase tracking-wider">Registro de proyecto</p><h2 className="text-xl font-bold text-[#202124]">{equipo ? "Editar proyecto" : "Nuevo proyecto"}</h2></div><button onClick={onClose} className="text-gray-500 hover:text-[#c8102e]"><X /></button></div><div className="p-5 sm:p-7 space-y-6"><div><p className="text-sm text-gray-500 mb-4">Estos campos son exactamente los mismos que contiene la plantilla de importación.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{CAMPOS.map(({ key, label, type }) => <label key={key} className="text-sm font-semibold text-gray-700">{label}<input required type={type ?? "text"} value={String(registro[key])} onChange={(e) => cambiar(key, e.target.value)} className={`${input} mt-1`} /></label>)}</div></div><div className="border-t pt-5"><h3 className="font-bold text-[#202124]">Documentos del proyecto</h3><p className="text-xs text-gray-500 mt-1 mb-3">Pega un enlace por documento. Se mantienen separados del formulario de registro.</p><div className="space-y-3">{DOCUMENTOS_EQUIPO.map(({ clave, nombre }) => { const actual = documentos.find((d) => d.clave === clave); return <div key={clave} className="grid grid-cols-1 sm:grid-cols-[150px_1fr] gap-2 items-center"><span className="text-sm font-semibold text-gray-700">{nombre}</span><input type="url" placeholder="https://drive.google.com/..." value={actual?.link ?? ""} onChange={(e) => setDocumentos((prev) => [...prev.filter((d) => d.clave !== clave), { clave, nombre, link: e.target.value, fechaActualizacion: new Date().toISOString() }])} className={input} /></div>; })}</div></div>{error && <p className="bg-red-50 border border-red-200 text-[#c8102e] px-3 py-2 text-sm">{error}</p>}<div className="flex flex-col-reverse sm:flex-row justify-end gap-2"><button onClick={onClose} className="px-4 py-2.5 border border-gray-300 text-gray-700">Cancelar</button><button onClick={guardar} disabled={guardando} className="px-4 py-2.5 bg-[#c8102e] text-white font-semibold disabled:opacity-50">{guardando ? "Guardando..." : "Guardar proyecto"}</button></div></div></div></div>;
}
